-- MySQL Script generated by MySQL Workbench
-- 05/24/18 13:52:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
	
-- -----------------------------------------------------
-- Schema emmanue4_TPI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emmanue4_TPI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emmanue4_TPI` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_cs  ;
USE `emmanue4_TPI` ;

-- -----------------------------------------------------
-- Table `emmanue4_TPI`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emmanue4_TPI`.`Type` ;

CREATE TABLE IF NOT EXISTS `emmanue4_TPI`.`Type` (
  `pkType` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`pkType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emmanue4_TPI`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emmanue4_TPI`.`User` ;

CREATE TABLE IF NOT EXISTS `emmanue4_TPI`.`User` (
  `pkUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `fkType` INT NOT NULL,
  PRIMARY KEY (`pkUser`),
  INDEX `fk_User_Type_idx` (`fkType` ASC),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC),
  CONSTRAINT `fk_User_Type`
    FOREIGN KEY (`fkType`)
    REFERENCES `emmanue4_TPI`.`Type` (`pkType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emmanue4_TPI`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emmanue4_TPI`.`Project` ;

CREATE TABLE IF NOT EXISTS `emmanue4_TPI`.`Project` (
  `pkProject` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(65000) NULL,
  `creationDate` DATETIME NOT NULL,
  `root` VARCHAR(45) NOT NULL,
  `topic` VARCHAR(45) NOT NULL,
  `fkUser` INT NOT NULL,
  PRIMARY KEY (`pkProject`),
  INDEX `fk_Project_User1_idx` (`fkUser` ASC),
  CONSTRAINT `fk_Project_User1`
    FOREIGN KEY (`fkUser`)
    REFERENCES `emmanue4_TPI`.`User` (`pkUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emmanue4_TPI`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emmanue4_TPI`.`Message` ;

CREATE TABLE IF NOT EXISTS `emmanue4_TPI`.`Message` (
  `pkMessage` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `fkUser` INT NOT NULL,
  `fkProject` INT NOT NULL,
  PRIMARY KEY (`pkMessage`),
  INDEX `fk_Message_User1_idx` (`fkUser` ASC),
  INDEX `fk_Message_Project1_idx` (`fkProject` ASC),
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`fkUser`)
    REFERENCES `emmanue4_TPI`.`User` (`pkUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_Project1`
    FOREIGN KEY (`fkProject`)
    REFERENCES `emmanue4_TPI`.`Project` (`pkProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emmanue4_TPI`.`State`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emmanue4_TPI`.`State` ;

CREATE TABLE IF NOT EXISTS `emmanue4_TPI`.`State` (
  `pkState` INT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(45) NULL,
  PRIMARY KEY (`pkState`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emmanue4_TPI`.`Version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emmanue4_TPI`.`Version` ;

CREATE TABLE IF NOT EXISTS `emmanue4_TPI`.`Version` (
  `pkVersion` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT(65000) NULL,
  `DevLog` TEXT(65000) NULL,
  `fkState` INT NOT NULL,
  `fkProject` INT NOT NULL,
  PRIMARY KEY (`pkVersion`),
  INDEX `fk_Version_State1_idx` (`fkState` ASC),
  INDEX `fk_Version_Project1_idx` (`fkProject` ASC),
  CONSTRAINT `fk_Version_State1`
    FOREIGN KEY (`fkState`)
    REFERENCES `emmanue4_TPI`.`State` (`pkState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Version_Project1`
    FOREIGN KEY (`fkProject`)
    REFERENCES `emmanue4_TPI`.`Project` (`pkProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `emmanue4_TPI` ;

-- -----------------------------------------------------
-- Placeholder table for view `emmanue4_TPI`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emmanue4_TPI`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `emmanue4_TPI`.`view1`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `emmanue4_TPI`.`view1` ;
DROP TABLE IF EXISTS `emmanue4_TPI`.`view1`;
USE `emmanue4_TPI`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
