-- MySQL Script generated by MySQL Workbench
-- 05/16/18 13:16:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EJSTPI
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EJSTPI` ;

-- -----------------------------------------------------
-- Schema EJSTPI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EJSTPI` DEFAULT CHARACTER SET utf8 ;
USE `EJSTPI` ;

-- -----------------------------------------------------
-- Table `EJSTPI`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EJSTPI`.`Type` ;

CREATE TABLE IF NOT EXISTS `EJSTPI`.`Type` (
  `pkType` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`pkType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EJSTPI`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EJSTPI`.`User` ;

CREATE TABLE IF NOT EXISTS `EJSTPI`.`User` (
  `pkUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `userName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `fkType` INT NOT NULL,
  PRIMARY KEY (`pkUser`),
  INDEX `fk_User_Type_idx` (`fkType` ASC),
  CONSTRAINT `fk_User_Type`
    FOREIGN KEY (`fkType`)
    REFERENCES `EJSTPI`.`Type` (`pkType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EJSTPI`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EJSTPI`.`Project` ;

CREATE TABLE IF NOT EXISTS `EJSTPI`.`Project` (
  `pkProject` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` BLOB NULL,
  `creationDate` DATETIME NOT NULL,
  `root` VARCHAR(45) NOT NULL,
  `topic` VARCHAR(45) NOT NULL,
  `fkUser` INT NOT NULL,
  PRIMARY KEY (`pkProject`),
  INDEX `fk_Project_User1_idx` (`fkUser` ASC),
  CONSTRAINT `fk_Project_User1`
    FOREIGN KEY (`fkUser`)
    REFERENCES `EJSTPI`.`User` (`pkUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EJSTPI`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EJSTPI`.`Message` ;

CREATE TABLE IF NOT EXISTS `EJSTPI`.`Message` (
  `pkMessage` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `fkUser` INT NOT NULL,
  PRIMARY KEY (`pkMessage`),
  INDEX `fk_Message_User1_idx` (`fkUser` ASC),
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`fkUser`)
    REFERENCES `EJSTPI`.`User` (`pkUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EJSTPI`.`State`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EJSTPI`.`State` ;

CREATE TABLE IF NOT EXISTS `EJSTPI`.`State` (
  `pkState` INT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(45) NULL,
  PRIMARY KEY (`pkState`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EJSTPI`.`Version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EJSTPI`.`Version` ;

CREATE TABLE IF NOT EXISTS `EJSTPI`.`Version` (
  `pkVersion` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` BLOB NULL,
  `DevLog` BLOB NULL,
  `fkState` INT NOT NULL,
  `fkProject` INT NOT NULL,
  PRIMARY KEY (`pkVersion`),
  INDEX `fk_Version_State1_idx` (`fkState` ASC),
  INDEX `fk_Version_Project1_idx` (`fkProject` ASC),
  CONSTRAINT `fk_Version_State1`
    FOREIGN KEY (`fkState`)
    REFERENCES `EJSTPI`.`State` (`pkState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Version_Project1`
    FOREIGN KEY (`fkProject`)
    REFERENCES `EJSTPI`.`Project` (`pkProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `EJSTPI` ;

-- -----------------------------------------------------
-- Placeholder table for view `EJSTPI`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EJSTPI`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `EJSTPI`.`view1`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `EJSTPI`.`view1` ;
DROP TABLE IF EXISTS `EJSTPI`.`view1`;
USE `EJSTPI`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
